[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
authors = ["sneyder J.H Rodriguez <sneyder.h.rodriguezgmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
